name: AdvLog
version: '1.0'
author: TSERATO
main: dev.tserato.advancedlogging.AdvancedLogging
description: Logs 150+ Events
api-version: '1.20'
commands:
  advlog:
    permission: advlog.use
    aliases: [al, advlog]