enable-console: false



#blocks
enable-break-console: false


block-break: true
block-break-console: false

block-burn: true
block-burn-console: false

block-can-build: true
block-can-build-console: false

block-damage: true
block-damage-console: false

block-dispense: true
block-dispense-console: false

block-fade: true
block-fade-console: false

block-form: true
block-form-console: false

block-from-to: true
block-from-to-console: false

block-grow: true
block-grow-console: false

block-piston-extend: true
block-piston-extend-console: false

block-piston-retract: true
block-piston-retract-console: false

block-place: true
block-place-console: false

block-redstone: true
block-redstone-console: false

block-spread: true
block-spread-console: false

block-leaves-decay: true
block-leaves-decay-console: false

block-note-play: true
block-note-play-console: false

block-sign-change: true
block-sign-change-console: false



#enchantment
enable-enchantment-console: false


enchant-enchantment: true
enchant-enchantment-console: false

enchant-prepare-enchantment: true
enchant-prepare-enchantment-console: false



#Entities
enable-entity-console: false


entity-spawn: true
entity-spawn-console: false

entity-creeper-power: true
entity-creeper-power-console: false

entity-break-door: true
entity-break-door-console: false

entity-block-change: true
entity-block-change-console: false

entity-combust: true
entity-combust-console: false

entity-create-portal: true
entity-create-portal-console: false

entity-damage-by-block: true
entity-damage-by-block-console: false

entity-damage-by-entity: true
entity-damage-by-entity-console: false

entity-death: true
entity-death-console: false

entity-explode: true
entity-explode-console: false

entity-interact: true
entity-interact-console: false

entity-portal-enter: true
entity-portal-enter-console: false

entity-portal-exit: true
entity-portal-exit-console: false

entity-regain-health: true
entity-regain-health-console: false

entity-shoot-bow: true
entity-shoot-bow-console: false

entity-tame: true
entity-tame-console: false

entity-target: true
entity-target-console: false

entity-teleport: true
entity-teleport-console: false

entity-exp-bottle: true
entity-exp-bottle-console: false

entity-explosion-prime: true
entity-explosion-prime-console: false

entity-food-level-change: true
entity-food-level-change-console: false

entity-item-despawn: true
entity-item-despawn-console: false

entity-pig-zap: true
entity-pig-zap-console: false

entity-player-death: true
entity-player-death-console: false

entity-potion-splash: true
entity-potion-splash-console: false

entity-sheep-dye-wool: true
entity-sheep-dye-wool-console: false

entity-sheep-regrow-wool: true
entity-sheep-regrow-wool-console: false

entity-slime-split: true
entity-slime-split-console: false



#Inventory
enable-inventory-console: false


inventory-brew: true
inventory-brew-console: false

inventory-craft-item: true
inventory-craft-item-console: false

inventory-furnace-burn: true
inventory-furnace-burn-console: false

inventory-furnace-smelt: true
inventory-furnace-smelt-console: false



#Player
enable-player-console: false


player-animation: true
player-animation-console: false

player-bed-enter: true
player-bed-enter-console: false

player-bed-leave: true
player-bed-leave-console: false

player-bucket-empty: true
player-bucket-empty-console: false

player-bucket-fill: true
player-bucket-fill-console: true

player-chat: true
player-chat-console: false

player-drop-item: true
player-drop-item-console: false

player-egg-throw: true
player-egg-throw-console: false

player-exp-change: true
player-exp-change-console: true

player-fish: true
player-fish-console: true

player-gamemode-change: true
player-gamemode-change-console: false

player-interact-entity: true
player-interact-entity-console: false

player-item-break: true
player-item-break-console: false

player-item-held: true
player-item-held-console: false

player-join: true
player-join-console: false

player-kick: true
player-kick-console: false

player-level-change: true
player-level-change-console: false

player-login: true
player-login-console: false

player-move: true
player-moce-console: false

player-item-pick: true
player-item-pick-console: false

player-pre-login: true
player-pre-login-console: false

player-quit: true
player-quit-console: false

player-respawn: true
player-respawn-console: false

player-shear-entity: true
player-shear-entity-console: false

player-teleport: true
player-teleport-console: false

player-toggle-flight: true
player-toggle-flight-console: false

player-toggle-sneak: true
player-toggle-sneak-console: false

player-toggle-sprint: true
player-toggle-sprint-console: false



#Vehicle
enable-vehicle-console: false


vehicle-block-collision: true
vehicle-block-collision-console: false

vehicle-create: true
vehicle-create-console: false

vehicle-damage: true
vehicle-damage-console: false

vehicle-destroy: true
vehicle-destroy-console: false

vehicle-enter: true
vehicle-enter-console: false

vehicle-exit: true
vehicle-exit-console: false

vehicle-move: true
vehicle-move-console: false



#Weather
enable-weather-console: false


weather-lightning: true
weather-lightning-console: false

weather-thunder: true
weather-thunder-console: false